import { useState, type ReactElement } from "react"
import { ExternalLinkIcon, ImageIcon } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { promptExampleOriginLabels, promptExampleStatusLabels, promptExampleVisibilityLabels, type PromptExample } from "@/contracts/prompt-example"

type Props = { promptExample: PromptExample; trigger: ReactElement }
function isSafeWebUrl(value: string | null): value is string { try { return Boolean(value && ["http:", "https:"].includes(new URL(value).protocol)) } catch { return false } }

export function PromptExampleDetailDrawer({ promptExample, trigger }: Props) {
  const [imageOpen, setImageOpen] = useState(false)
  const imageUrl = isSafeWebUrl(promptExample.examplePreviewUrl) ? promptExample.examplePreviewUrl : null
  const sourceUrl = isSafeWebUrl(promptExample.sourceUrl) ? promptExample.sourceUrl : null
  return <Sheet><SheetTrigger render={trigger} /><SheetContent side="right" className="w-full gap-0 p-0 sm:!max-w-5xl"><SheetHeader className="border-b px-6 py-5"><SheetTitle>{promptExample.title}</SheetTitle><SheetDescription>提示词与图例详情</SheetDescription></SheetHeader><div className="min-h-0 flex-1 overflow-y-auto px-6 py-5"><div className="grid gap-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(18rem,0.85fr)]"><section><h3 className="mb-2 text-sm font-medium">正向提示词</h3><pre className="max-h-[58vh] overflow-auto whitespace-pre-wrap rounded-xl border bg-muted/25 p-4 font-sans text-sm leading-6">{promptExample.promptText}</pre>{promptExample.negativePrompt && <><h3 className="mb-2 mt-5 text-sm font-medium">负向提示词</h3><pre className="whitespace-pre-wrap rounded-xl border bg-muted/25 p-4 font-sans text-sm leading-6">{promptExample.negativePrompt}</pre></>}</section><section><h3 className="mb-2 text-sm font-medium">图例图片</h3>{imageUrl ? <button type="button" onClick={() => setImageOpen(true)} className="block aspect-[4/5] w-full overflow-hidden rounded-xl border bg-muted/25"><img src={imageUrl} alt={`${promptExample.title} 图例`} className="size-full object-cover transition-transform hover:scale-[1.02]" /></button> : <div className="flex aspect-[4/5] items-center justify-center rounded-xl border bg-muted/25 text-sm text-muted-foreground"><ImageIcon className="mr-2 size-5" />暂无图例</div>}<p className="mt-2 text-xs text-muted-foreground">点击图片可放大预览</p></section></div><div className="mt-6 grid gap-4 border-t pt-5 sm:grid-cols-2"><Info label="来源" value={promptExampleOriginLabels[promptExample.originType]} /><Info label="整理状态" value={promptExampleStatusLabels[promptExample.status]} /><Info label="共享标记" value={promptExampleVisibilityLabels[promptExample.visibility]} /><Info label="原作者 / 来源账号" value={promptExample.sourceAuthor ?? "—"} /><div className="sm:col-span-2"><p className="text-xs text-muted-foreground">标签</p><div className="mt-2 flex flex-wrap gap-1">{promptExample.tags.length ? promptExample.tags.map((tag) => <Badge key={tag} variant="secondary">{tag}</Badge>) : "—"}</div></div>{sourceUrl && <div className="sm:col-span-2"><Button variant="outline" render={<a href={sourceUrl} target="_blank" rel="noreferrer" />}><ExternalLinkIcon />打开原始链接</Button></div>}{promptExample.notes && <div className="sm:col-span-2"><p className="text-xs text-muted-foreground">备注</p><p className="mt-1 whitespace-pre-wrap text-sm">{promptExample.notes}</p></div>}</div></div></SheetContent><Dialog open={imageOpen} onOpenChange={setImageOpen}><DialogContent className="max-w-[92vw] border-0 bg-black p-2 sm:max-w-5xl"><DialogTitle className="sr-only">{promptExample.title} 图例预览</DialogTitle>{imageUrl && <img src={imageUrl} alt={`${promptExample.title} 图例`} className="max-h-[86vh] w-full object-contain" />}</DialogContent></Dialog></Sheet>
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value}</p></div> }
