import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { CloudCogIcon, LockKeyholeIcon, ServerCogIcon } from "lucide-react"
import { toast } from "sonner"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { storageProviderDefinitions } from "@/config/storage-providers"
import { getSupabaseEndpointHostname, isSupabaseConfigured } from "@/lib/supabase"
import { getContentWorkspace } from "@/services/content-workspace-service"
import { getStorageProviderConfigs, setDefaultStorageProvider } from "@/services/storage-provider-service"

export function SettingsPage() {
  const queryClient = useQueryClient(), workspace = useQuery({ queryKey: ["content-workspace"], queryFn: getContentWorkspace }), organizationId = workspace.data?.organization?.id
  const configs = useQuery({ queryKey: ["storage-provider-configs", organizationId], queryFn: () => getStorageProviderConfigs(organizationId!), enabled: Boolean(organizationId) })
  const changeDefault = useMutation({ mutationFn: (provider: typeof storageProviderDefinitions[number]["key"]) => setDefaultStorageProvider(organizationId!, provider), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["storage-provider-configs"] }); toast.success("默认存储已切换；新上传文件将使用该提供商。") }, onError: (error) => toast.error(error instanceof Error ? error.message : "切换失败。") })
  const active = configs.data?.find((config) => config.isDefault), endpointHostname = getSupabaseEndpointHostname()
  return <div className="space-y-6"><PageHeader eyebrow="Workspace" title="系统设置" description="管理外部服务连接与素材对象存储路由。密钥仅保存在服务端。" />
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader className="border-b"><div className="flex justify-between"><CardTitle>Supabase</CardTitle><Badge variant={isSupabaseConfigured ? "default" : "outline"}>{isSupabaseConfigured ? "已连接" : "未配置"}</Badge></div><CardDescription>认证、业务数据、关系与审计</CardDescription></CardHeader><CardContent className="space-y-3 pt-5 text-sm"><Line label="项目端点" value={endpointHostname ?? "未配置"} /><Line label="浏览器密钥" value={isSupabaseConfigured ? "Publishable Key 已配置" : "未配置"} /></CardContent></Card><Card><CardHeader className="border-b"><div className="flex justify-between"><CardTitle>当前默认资产存储</CardTitle><Badge variant={active?.status === "ready" ? "default" : "outline"}>{active?.status === "ready" ? "已启用" : "加载中"}</Badge></div><CardDescription>切换后只影响新上传的对象</CardDescription></CardHeader><CardContent className="pt-5"><div className="flex items-center gap-3"><CloudCogIcon className="size-7 text-primary" /><div><p className="font-medium">{storageProviderDefinitions.find((item) => item.key === active?.provider)?.name ?? "读取中…"}</p><p className="mt-1 text-sm text-muted-foreground">{active ? `${active.bucket}/${active.objectPrefix}` : ""}</p></div></div></CardContent></Card></div>
    <Card><CardHeader className="border-b"><div className="flex items-center gap-2"><ServerCogIcon className="size-5" /><CardTitle>对象存储提供商</CardTitle></div><CardDescription>选择的提供商会成为新上传对象的写入目标；旧对象仍按其原位置保留。</CardDescription></CardHeader><CardContent className="divide-y p-0">{storageProviderDefinitions.map((provider) => { const config = configs.data?.find((item) => item.provider === provider.key), defaulted = config?.isDefault; return <div key={provider.key} className="grid gap-4 px-6 py-5 md:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2"><p className="font-medium">{provider.name}</p><Badge variant={defaulted ? "default" : "outline"}>{defaulted ? "当前默认" : config?.status === "ready" ? "已验证" : "待配置"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{config ? `${config.bucket}/${config.objectPrefix}` : provider.requiredConfiguration.join(" · ")}</p><p className="mt-1 text-xs text-muted-foreground">{provider.notes}</p></div>{workspace.data?.canManage && <Button variant={defaulted ? "outline" : "default"} disabled={defaulted || config?.status !== "ready" || changeDefault.isPending} onClick={() => changeDefault.mutate(provider.key)}>{defaulted ? "正在使用" : "设为默认"}</Button>}</div> })}</CardContent></Card>
    <Card><CardHeader className="border-b"><div className="flex items-center gap-2"><LockKeyholeIcon className="size-5" /><CardTitle>安全路由</CardTitle></div></CardHeader><CardContent className="pt-5 text-sm leading-6 text-muted-foreground">七牛上传通过已部署的 Edge Function 签发 5 分钟有效、限定单个对象键的 UploadToken。AK/SK 不会返回浏览器；后续接入 OSS、COS 或 R2 也复用同一个对象存储路由。</CardContent></Card>
  </div>
}
function Line({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value}</span></div> }
