import type { StorageProviderKey } from "@/config/storage-providers"
import { getSupabaseClient } from "@/lib/supabase"

export type StorageProviderConfig = { id: number; organizationId: string; provider: StorageProviderKey; bucket: string; objectPrefix: string; endpoint: string | null; publicBaseUrl: string | null; status: "ready" | "pending_secret" | "disabled"; isDefault: boolean }
type Row = { id: number; organization_id: string; provider: StorageProviderKey; bucket: string; object_prefix: string; endpoint: string | null; public_base_url: string | null; status: StorageProviderConfig["status"]; is_default: boolean }
function client() { const value = getSupabaseClient(); if (!value) throw new Error("Supabase 尚未配置。"); return value }
function map(row: Row): StorageProviderConfig { return { id: row.id, organizationId: row.organization_id, provider: row.provider, bucket: row.bucket, objectPrefix: row.object_prefix, endpoint: row.endpoint, publicBaseUrl: row.public_base_url, status: row.status, isDefault: row.is_default } }
export async function getStorageProviderConfigs(organizationId: string) { const { data, error } = await client().from("storage_provider_configs").select("id, organization_id, provider, bucket, object_prefix, endpoint, public_base_url, status, is_default").eq("organization_id", organizationId).order("provider"); if (error) throw new Error("无法读取对象存储配置。"); return ((data ?? []) as Row[]).map(map) }
export async function setDefaultStorageProvider(organizationId: string, provider: StorageProviderKey) { const supabase = client(); const { data: selected, error: selectedError } = await supabase.from("storage_provider_configs").select("id, status").eq("organization_id", organizationId).eq("provider", provider).single(); if (selectedError || selected.status !== "ready") throw new Error("该存储尚未准备就绪。"); const { error: clearError } = await supabase.from("storage_provider_configs").update({ is_default: false }).eq("organization_id", organizationId).eq("is_default", true); if (clearError) throw new Error("无法更新默认存储。"); const { error } = await supabase.from("storage_provider_configs").update({ is_default: true }).eq("id", selected.id).eq("organization_id", organizationId); if (error) throw new Error("无法设为默认存储。") }
