import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'

test.use({ actionTimeout: 15000 })
const fixturePath = process.env.CONTENT_E2E_FIXTURE
// Explicit disposable account only. Never use a personal production session.
test('cloud content: author, review, plan, export, publish and review metrics', async ({ page }) => {
  test.skip(!fixturePath, 'Set CONTENT_E2E_FIXTURE to a disposable test account JSON')
  test.setTimeout(120000)
  const fixture = JSON.parse(readFileSync(fixturePath!, 'utf8')) as { email: string; password: string }
  await page.goto('/login')
  await page.locator('#email').fill(fixture.email)
  await page.locator('#password').fill(fixture.password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/dashboard/, { timeout: 20000 })
  await page.goto('/content/projects')
  await page.getByRole('button', { name: '新建内容项目' }).click()
  await page.getByLabel('项目名称').fill('验收：企业 AI 内容流程')
  await page.getByLabel('创作 Brief').fill('解释企业 AI 如何从试验走向生产。引用需要人工核实。')
  await page.getByRole('button', { name: '保存项目' }).click()
  await expect(page).toHaveURL(/content\/projects\//)
  const projectUrl = page.url()
  await page.getByRole('button', { name: '创建母稿' }).click()
  await page.getByLabel('正文（Markdown）').fill('## 核心观点\n企业 AI 项目需要明确的流程、责任与验收。\n\n[待核实] 补充真实案例。')
  await page.getByRole('button', { name: '保存新版本' }).click()
  await expect(page.getByText('有未保存修改')).toHaveCount(0)
  await page.getByRole('button', { name: '提交审核', exact: true }).click()
  await page.getByRole('button', { name: '审核通过', exact: true }).click()
  await expect(page.getByText('已通过', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('正文（Markdown）')).toHaveValue(/企业 AI 项目/)
  await page.getByLabel('新平台版本').selectOption('x')
  await page.getByRole('button', { name: '从母稿创建平台版本' }).click()
  await page.getByRole('button', { name: '提交审核', exact: true }).click()
  await page.getByRole('button', { name: '审核通过', exact: true }).click()
  await expect(page.getByText('已通过', { exact: true })).toBeVisible()
  await page.goto('/publishing/channels')
  await page.getByLabel('发布平台').selectOption('x')
  await page.getByLabel('账号名称').fill('验收账号 X')
  await page.getByRole('button', { name: '登记账号', exact: true }).click()
  await expect(page.getByText('验收账号 X', { exact: true })).toBeVisible()
  await page.goto('/publishing/plans')
  await page.getByLabel('已审核的平台稿件').selectOption({ index: 1 })
  await page.getByLabel('发布账号', { exact: true }).selectOption({ index: 1 })
  await page.getByRole('button', { name: '保存发布计划' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出发布版本', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/publication-.*\.md/)
  await page.getByLabel('实际发布链接').fill('https://example.com/spark-acceptance')
  await page.getByRole('button', { name: '确认已人工发布' }).click()
  await expect(page.getByRole('link', { name: '打开已发布内容' })).toBeVisible()
  await page.getByText('回填数据与复盘', { exact: true }).click()
  await page.getByLabel('阅读 / 播放', { exact: true }).fill('120')
  await page.getByLabel('复盘结论与下次实验').fill('下次用真实案例替换抽象描述。')
  await page.getByRole('button', { name: '保存观察快照' }).click()
  await expect(page.getByText(/阅读 \/ 播放 120 ·/)).toBeVisible()
  await page.goto('/analytics')
  await expect(page.getByText(/阅读\/播放 120/)).toBeVisible()
  await page.screenshot({ path: '/tmp/spark-content-analytics.png', fullPage: true })
  await page.goto(projectUrl)
  await page.getByRole('button', { name: 'X', exact: true }).click()
  await page.getByLabel('正文（Markdown）').fill('改稿后的版本需要重新审核。')
  await page.getByRole('button', { name: '保存新版本' }).click()
  await expect(page.getByRole('button', { name: '提交审核', exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/spark-content-editor.png', fullPage: true })
})
